"""empty message

Revision ID: 172b32d808c4
Revises: 72bd78e6886a
Create Date: 2022-05-23 11:01:56.356703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '172b32d808c4'
down_revision = '72bd78e6886a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.drop_column('artists', 'seeking_talent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_talent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('artists', 'seeking_venue')
    # ### end Alembic commands ###
